RedHat-SP-Security/tang-operator-tests

Sanity/runtest.sh

Include DISABLE_BUNDLE_UNINSTALL_TESTS option

---

README.md

Add steps to run test suite with different options

---

Sanity/runtest.sh

Fix malware detection tests on minikube root mode

---

Sanity/runtest.sh

Overwrite also images in scripts

---

README.md

Include default version tested by test suite

---

.github/workflows/yamllint.yaml

Limit yamllint Github Action to .yaml files

---

Sanity/runtest.sh

Dump the amount of alerts detected

---

Sanity/runtest.sh

Fix most of the issues returned by shellcheck

---

README.md

Include references to tmt/fmf in README.md

---

README.md

Clarify Minikube is the default platform to use

---

Makefile
Sanity/DAST_test/Makefile
Sanity/DAST_test/runtest.sh
Sanity/Makefile
Sanity/configuration_test/Makefile
Sanity/functional_test/Makefile
Sanity/functional_test/runtest.sh
Sanity/key_management_test/Makefile
Sanity/legacy_test/Makefile
Sanity/malware_detection_test/Makefile
Sanity/malware_detection_test/runtest.sh
Sanity/scalability_test/Makefile
Setup/clean_cluster/Makefile
Setup/clean_cluster/runtest.sh
Setup/creating_test_namespace/Makefile
TestHelpers/functions.sh

Include Makefile based test execution

---

README.md

Align README.md with current execution status

---

Setup/creating_test_namespace/runtest.sh
TestHelpers/functions.sh

Include error state option on Pod state checking

---

Setup/creating_test_namespace/runtest.sh
TestHelpers/functions.sh

Include function to check state during some time

---

TestHelpers/functions.sh

Alert about long time on catalog installation

---

Setup/creating_test_namespace/runtest.sh

Fail on controller startup errors

---

Sanity/malware_detection_test/runtest.sh

Ensure unique image is provided to malware test

---

Setup/clean_cluster/runtest.sh
TestHelpers/functions.sh

Fix cleanup by accessing tmp directory

---

Setup/clean_cluster/runtest.sh

Include correct method for pod name retrieval

---

Sanity/DAST_test/runtest.sh

Use latest stable rapidast container

---

Sanity/functional_test/runtest.sh
TestHelpers/reg_test/func_test/none_cluster_ip/daemons_v1alpha1_pv.yaml
TestHelpers/reg_test/func_test/none_cluster_ip/daemons_v1alpha1_tangserver.yaml

Include None ClusterIP test

---

README.md

Fix and groom README.md

---

Setup/creating_test_namespace/runtest.sh

Add image mirror digest when working on Konflux
